[build]
publish = "frontend"
command = "echo 'No build command for static files'"

[functions]
directory = "netlify/functions"

[redirects]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
