[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[build]
command = "npm run build:frontend"
publish = "frontend

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"
